on:
  schedule:
    - cron: '0 7 1/14 * *'

jobs:
  scheduled_email_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11.1
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.1"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: install playwright dependencies
        run: |
          playwright install
          playwright install-deps
      - name: run code
        run: |
          python -c'import scheduler; scheduler.notify_lobbyists_actions_by_mail()'